### ISSUE TITLE
Update new prompt -error

### ISSUE THREAD

**Issue by thejohnd0e** [corbin-hayden13/SD-Prompt-Enhancer#28]
<img width="974" alt="Screenshot - 2023-06-07 08 20 19" src="https://github.com/corbin-hayden13/SD-Prompt-Enhancer/assets/115493464/9843115b-dc74-410e-8d70-b1d75c4271ae">

I get an error when I press the "Update new prompt" button.

**Comment by corbin-hayden13** [comment]
Is your issue still persisting?  Could you please provide more details about what you were trying to do when the error occurred, as well as what values you had in your dropdown menus?

**Comment by thejohnd0e** [comment]
> Is your issue still persisting? Could you please provide more details about what you were trying to do when the error occurred, as well as what values you had in your dropdown menus?

Yes, the error still exists
![image](https://github.com/corbin-hayden13/SD-Prompt-Enhancer/assets/115493464/ae85952e-415b-44fd-b2a0-c6f50920fadc)
---
![image](https://github.com/corbin-hayden13/SD-Prompt-Enhancer/assets/115493464/65d835f8-3fdf-4875-b038-a78ad02f1f5e)

**Comment by thejohnd0e** [comment]
![image](https://github.com/corbin-hayden13/SD-Prompt-Enhancer/assets/115493464/4a1613f3-2df3-4c48-95f1-275581c6236a)
 the error appears when trying to apply any values

**Comment by thejohnd0e** [comment]
So, now i found a solution. The button 
![image](https://github.com/corbin-hayden13/SD-Prompt-Enhancer/assets/115493464/bbb2aa32-6c2b-44f9-b86b-352cf5a3330b)
solves the issue if it appears.

**Comment by corbin-hayden13** [comment]
I'll take a look and make sure it doesn't come up in the first place, but I'm glad you found a workaround for the moment!

**Comment by corbin-hayden13** [comment]
Thank you for the very thorough error report! I implemented an if statement to catch any None values from the dropdowns so it shouldn't throw an error anymore when executing.  While I was not able to replicate the issue myself, I believe this is due to an issue with Gradio not loading the dropdown elements fast enough on it's end, so the values are not updated in code even though there are visual changes.  This is why I think clear all dropdowns works to fix it, because the dropdowns are all reset to nothing and hence initialized in code.  I'll look into more ways to remedy this issue, but hopefully this you won't encounter this in the future.
